# Generated by Django 4.2.2 on 2023-06-30 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('interest_1', models.CharField(default='', max_length=50)),
                ('interest_1_score', models.IntegerField()),
                ('interest_2', models.CharField(default='', max_length=50)),
                ('interest_2_score', models.IntegerField()),
                ('interest_3', models.CharField(default='', max_length=50)),
                ('interest_3_score', models.IntegerField()),
                ('interest_4', models.CharField(default='', max_length=50)),
                ('interest_4_score', models.IntegerField()),
                ('interest_5', models.CharField(default='', max_length=50)),
                ('interest_5_score', models.IntegerField()),
                ('interest_6', models.CharField(default='', max_length=50)),
                ('interest_6_score', models.IntegerField()),
                ('status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
