# Generated by Django 4.2.2 on 2023-06-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_userdetail_interest_1_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='interest_1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='interest_2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='interest_3_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='interest_4_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='interest_5_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='interest_6_score',
            field=models.IntegerField(default=0),
        ),
    ]
