# Generated by Django 4.2.2 on 2023-07-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_room_chatmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='ChatRoom',
        ),
    ]
