# Generated by Django 4.2.2 on 2023-07-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_chatmsg_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmsg',
            name='sender',
            field=models.CharField(max_length=20),
        ),
    ]
