# Generated by Django 4.2.2 on 2023-07-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_alter_chatmsg_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_1',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_1_score',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_2',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_2_score',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_3',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_3_score',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_4',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_4_score',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_5',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_5_score',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_6',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='interest_6_score',
        ),
    ]
